### PR TITLE
chore(action): no need to checkout

### PR DESCRIPTION
**Pull request by FedeDP**

### CODE REVIEW

**Comment by FedeDP** [comment]
Ok the test worked fine: https://github.com/falcosecurity/libs/actions/runs/7841427978/job/21397737318
Ansible playbooks were found (ie: the repo was actually cloned) and the correct version was used (ie: the provided hash). Workflow failed because it could not find images with provided hash, since it comes from a commit from this PR.

**Review by therealbobo — APPROVED** [review]

**Pull request merged**
