### PR TITLE
vote: update(OWNERS): add therealbobo (Roberto Scolaro) to approvers

### PR DESCRIPTION
**Pull request by therealbobo**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it:**

Proposing myself as kernel-testing maintainer (as per 2023-09-13 community call discussion) and continue supporting the project in the following main areas:

- image maintenance/creation
- code reviews + bug fixes

### CODE REVIEW

**Comment by FedeDP** [comment]
Big +1 from me! Roby was the king of generating docker images, and made such a terrific job in that area!
Thank you very much, happy to see you on board!

**Comment by Andreagit97** [comment]
Big +1 for me!

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
We need test-infra and evolution PRs !

**Pull request merged**
